[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "public"

 [functions]
   directory = "dist/netlify/functions"

[[redirects]]
  from = "/graphql"
  to = "/.netlify/functions/graphql"
  status = 200